export const LIMITS = {
  REFERRAL_TREE_MAX_DEPTH: 20,
  MIN_AGE_GENERAL: 13,
  MAX_AGE_GENERAL: 120,
  MIN_AGE_PARTNER: 18,
  MIN_NAME_LENGTH: 2,
  VERIFICATION_CODE_EXPIRY_MS: 10 * 60 * 1000,
} as const;
